#!/usr/bin/env bash
# Builds the community track manifest (NetTarget/CommunityTracks.tsv) from a
# folder of .trk files by running each through the community validator.
#
#   scripts/generate-community-manifest.sh VALIDATOR TRACK_DIR [OUTPUT]
#
# A track is listed only if it loads and has a playable start (see
# `HoverNetTrackValidator --community`). Tracks that fail are reported on stderr
# and left out, so the game never offers something it cannot start. The track
# files themselves are never modified.
set -euo pipefail

validator=$(realpath "${1:?path to HoverNetTrackValidator required}")
track_dir=$(realpath "${2:?directory of .trk files required}")
output=${3:-NetTarget/CommunityTracks.tsv}
export SDL_VIDEODRIVER=${SDL_VIDEODRIVER:-dummy}

rows=$(mktemp)
official=$(mktemp)
trap 'rm -f "$rows" "$official"' EXIT
accepted=0
rejected=0
skipped=0

# Names of the bundled tracks. A community track with the same name is never
# offered (the official one always wins), and in this library such tracks are
# copies of the bundled ones, so skipping them loses nothing.
official_dir=${OFFICIAL_TRACK_DIR:-NetTarget/Tracks}
if [[ -d $official_dir ]]; then
  for official_file in "$official_dir"/*.trk; do
    basename "$official_file" .trk | tr 'A-Z' 'a-z'
  done >"$official"
fi

while IFS= read -r -d '' file; do
  name=$(basename "$file" .trk)
  if grep -qxF -- "$(printf '%s' "$name" | tr 'A-Z' 'a-z')" "$official"; then
    echo "skipped (same name as a bundled track): $name" >&2
    skipped=$((skipped + 1))
    continue
  fi
  if result=$(timeout 60 "$validator" --community --manifest "$file" "$name" 2>/dev/null); then
    row=$(printf '%s\n' "$result" | grep -m1 '^MANIFEST' | cut -f2-) || row=
    if [[ -n $row ]]; then
      # Download details: decompressed size, SHA-256, a hash-based asset name and
      # the compressed size (gzip -n -9 is deterministic). The shard is added
      # after sorting, below.
      bytes=$(stat -c %s "$file")
      sha=$(sha256sum "$file" | cut -d' ' -f1)
      gzbytes=$(gzip -n -9 -c "$file" | wc -c)
      printf '%s\t%s\t%s\t%s\t%s\n' "$row" "$bytes" "$sha" "${sha:0:16}" "$gzbytes" >>"$rows"
      accepted=$((accepted + 1))
      continue
    fi
  fi
  echo "rejected: $name" >&2
  rejected=$((rejected + 1))
done < <(find "$track_dir" -maxdepth 1 -name '*.trk' -print0)

{
  echo "# HoverNet community track manifest -- generated by scripts/generate-community-manifest.sh"
  echo "# name<TAB>mode (race|freeplay)<TAB>starts<TAB>rooms<TAB>validator warnings<TAB>bytes<TAB>sha256<TAB>shard<TAB>asset<TAB>gzip bytes"
  echo "# Hosted as <download base>/<shard>/<asset>.trk.gz ; see scripts/package-community-tracks.sh"
  # Shards of 500 keep each release under GitHub's per-release asset limit.
  LC_ALL=C sort -t "$(printf '\t')" -k1,1 "$rows" |
    awk -F'\t' -v OFS='\t' '{ shard = "community-tracks-" int((NR - 1) / 500 + 1); print $1, $2, $3, $4, $5, $6, $7, shard, $8, $9 }'
} >"$output"

echo "manifest: $accepted track(s) listed, $skipped skipped as bundled, $rejected rejected -> $output" >&2
