#!/usr/bin/env python3
"""Generate the Manta craft mesh using symmetric closed patch grids."""

from math import cos, pi, sin
from pathlib import Path

# Original craft artwork. These bitmaps were authored for the engine palette
# and contain the dithering/details seen on the basic craft.
BUMPER = 20
COCKPIT = 21
MOTOR = 22
MOTOR_ARM = 23
MOTOR_FIRE = 24
DRIVER_HEAD = 25
DRIVER_NECK = 26
SEGMENTS = 16


def ring(cx, cy, z, rx, ry, segments=SEGMENTS, phase=0.0):
    return [
        (round(cx + rx * cos(phase + 2 * pi * i / segments)),
         round(cy + ry * sin(phase + 2 * pi * i / segments)), z)
        for i in range(segments + 1)
    ]


def patch(lines, rows, material):
    width = len(rows[0])
    assert all(len(row) == width for row in rows)
    lines.extend(("PATCH", f"{width} {len(rows)}"))
    for row in rows:
        lines.extend(f"{x:5d} {y:5d} {z:4d}" for x, y, z in row)
    lines.append(str(material))


def turbine(lines, y):
    rings = []
    for x, radius in ((-620, 220), (-830, 245), (-1050, 195)):
        circle = []
        for i in range(SEGMENTS + 1):
            angle = 2 * pi * i / SEGMENTS
            circle.append((x, y + round(radius * cos(angle)),
                           780 + round(radius * sin(angle))))
        rings.append(circle)
    patch(lines, rings, MOTOR)
    patch(lines, [[(-1060, y - 160, 755), (-1060, y + 160, 755)],
                  [(-1060, y - 160, 805), (-1060, y + 160, 805)]], MOTOR_ARM)
    patch(lines, [[(-1060, y - 25, 625), (-1060, y + 25, 625)],
                  [(-1060, y - 25, 935), (-1060, y + 25, 935)]], MOTOR_ARM)


def flame(lines, y, length, radius):
    nozzle = -1050
    end = nozzle - length
    patch(lines, [[(nozzle, y - radius, 780), (nozzle, y + radius, 780)],
                  [(nozzle - length // 2, y - radius // 2, 780),
                   (nozzle - length // 2, y + radius // 2, 780)],
                  [(end, y - 10, 780), (end, y + 10, 780)]], MOTOR_FIRE)
    patch(lines, [[(nozzle, y, 780 - radius), (nozzle, y, 780 + radius)],
                  [(nozzle - length // 2, y, 780 - radius // 2),
                   (nozzle - length // 2, y, 780 + radius // 2)],
                  [(end, y, 770), (end, y, 790)]], MOTOR_FIRE)
    glow = radius * 2 // 3
    patch(lines, [[(-1015, y - glow, 780 - glow), (-1015, y + glow, 780 - glow)],
                  [(-1065, y - glow, 780 + glow), (-1065, y + glow, 780 + glow)]], MOTOR_FIRE)


def generate():
    lines = [
        "// Generated by generate_manta_mesh.py.",
        "// Inspired by the original craft: rounded base, low dome, exposed driver.",
        "SEQUENCE", "FRAME",
    ]

    # One-piece elliptical hover base: domed top, deep outer wall, closed bottom.
    patch(lines, [ring(0, 0, 520, 275, 225),
                  ring(0, 0, 440, 790, 650),
                  ring(0, 0, 300, 1100, 900)], BUMPER)
    patch(lines, [ring(0, 0, 300, 1100, 900),
                  ring(0, 0, 20, 1100, 900)], BUMPER)
    patch(lines, [ring(0, 0, 20, 1100, 900),
                  ring(0, 0, 55, 720, 590),
                  ring(0, 0, 120, 260, 210)], BUMPER)

    # Low red center dome, matching the reference craft's simple solid body.
    patch(lines, [ring(100, 0, 900, 55, 45, phase=pi),
                  ring(80, 0, 680, 470, 380, phase=pi),
                  ring(20, 0, 420, 760, 610, phase=pi)], COCKPIT)

    # Exposed driver helmet above a small black cockpit collar.
    patch(lines, [ring(80, 0, 760, 210, 170, 12),
                  ring(80, 0, 820, 145, 115, 12)], BUMPER)
    patch(lines, [ring(80, 0, 790, 65, 58, 12, phase=pi),
                  ring(80, 0, 930, 72, 64, 12, phase=pi)], DRIVER_NECK)
    patch(lines, [ring(80, 0, 900, 45, 40, 12, phase=pi),
                  ring(80, 0, 1030, 150, 135, 12, phase=pi),
                  ring(80, 0, 1170, 115, 105, 12, phase=pi),
                  ring(80, 0, 1250, 18, 16, 12, phase=pi)], DRIVER_HEAD)

    # Two compact, smooth rear turbine pods.
    turbine(lines, 470)
    turbine(lines, -470)

    # Powered sequence is composited over sequence 0 by both renderers.
    lines.extend(("SEQUENCE", "FRAME"))
    flame(lines, 470, 480, 150)
    flame(lines, -470, 480, 150)
    lines.append("FRAME")
    flame(lines, 470, 650, 185)
    flame(lines, -470, 650, 185)
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    Path(__file__).with_name("Manta.msh").write_text(generate(), encoding="ascii")
